apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echo-2
  name: echo-2
  annotations:
      argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-2
    spec:
      containers:
      - image: fl64/echo-http:0.0.5
        name: echo-http
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: echo-3
  name: echo-3
  annotations:
      argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-3
    spec:
      containers:
      - image: fl64/echo-http:0.0.5
        name: echo-http
        resources: {}
status: {}
